### ISSUE TITLE
Does not show hour from midnight to 1am

### ISSUE THREAD

**Issue by DENightOne** [gaco79/gcclock-words#4]
Firstly thanks for an awesome card for HA.  I was working late last night and noticed that the card does not show the hours between 12am and 1am, I am no coder but looking at the javascript i notice that you have no settings for when the hour is (0). All European computer clocks are set to 24 hour clocks so between 12am and 1am the clocks will always read 00:01 - 00:59.

I added this change to your code:
`<span class="word" style="${this.isHour(12) || this.isHour(0)}">twelve</span>
 <span class="word" style="${this.isMinute(0)}">o'clock</span>`

change my time on my PC to 13 hours ahead to check if it works.... it how shows "twelve" meaning 12am like it should and also shows 12pm as it was before change.

Hope this helps anyone who stays up late like me.

**Comment by gaco79** [comment]
Thanks! I'll fix it when I've got a spare minute!

**Comment by DENightOne** [comment]
Ok I am getting a little closer, the change that I made only seemed to work (because of time).... so what happens is your code works perfectly for the first half and hour meaning 0:01 to 0:30 and then the code moves from "past" to "to"... in the console log it shows that t is 12 the whole time meaning the whole hour. but when the function in the code changes from "past" to "to" the "twelve" does not change to "one" in the display..... as I said before I am far from a developer and I am slowly trying to figure it out. If i fix it I will post an update

**Comment by DENightOne** [comment]
I have change the logic in the function and its to work for all times...... as i said before I am a hobby home assistant user and have no real knowledge of coding, so this is your warning.   

I have change the following within the function: `isHour(t){
    let e = this.currentTime[0] % 12;
    if (e === 0) e = 12;
    if (this.currentTime[1] > 32) e++;
    if (e === 13) e = 1; // Adjust for the hour increment past 12
    return e === t ? this.activeStyle : this.inactiveStyle;
}`
